import Home from "./antidrug-home.png";
import Question from "./question.png";
import Result from "./result.png";
import Tutorial from "./tutorial.png";
import Wrong from "./wrong.png";
import Correct from "./correct.png";
import User from "./user.png";
export const AntidrugHomeImgSrc = Home.src;
export const QuestionImgSrc = Question.src;
export const ResultImgSrc = Result.src;
export const TutorialImgSrc = Tutorial.src;
export const WrongImgSrc = Wrong.src;
export const CorrectImgSrc = Correct.src;
export const UserImgSrc = User.src;
