import Home from "./home.png";
import WeProvide from "./weProvide.png";
import LightMode from "./lightMode.png";
import OurClient from "./ourClient.png";
import Responsive from "./responsive.png";
import ContactUs from "./contactUs.png";
export const CooltechHomeImgSrc = Home.src;
export const CooltechWeProvideImgSrc = WeProvide.src;
export const CooltechLightModeImgSrc = LightMode.src;
export const CooltechOurClientImgSrc = OurClient.src;
export const CooltechResponsiveImgSrc = Responsive.src;
export const CooltechContactUsImgSrc = ContactUs.src;
